### ISSUE TITLE
MEDIUM: unclear administration policy

### ISSUE THREAD

**Issue by vladislavSailor** [vladislavpetushkov/axly-smartcontract#12]
1 админ владелец axly второй админ владелец land по договоренности менять контракт могут только они вдвоем, на land так же будет.
3 админ, доп админ для axly с возможность выключить, включить контракт и пулы и для инста пула.

**Comment by deemru** [comment]
Возможно так и надо назвать ключи?

**Comment by vladislavpetushkov** [comment]
fixed
