### ISSUE TITLE
HIGH: `liquidate()` mechanic looks strange as an user just lose his position funds without benefits

### ISSUE THREAD

**Issue by vladislavpetushkov** [vladislavpetushkov/axly-smartcontract#2]
Ликвидация происходит, когда здоровье пользователя приближается к определенной отметки, тут никаких плюшек для пользователя быть не может.

**Comment by deemru** [comment]
В коде это не отражено.

**Comment by vladislavpetushkov** [comment]
на этапе mvp решили не делать проверку health. далее перенесем. verifier лендинга не позволит менять его код без нас.

**Comment by deemru** [comment]
Хорошо, однако лучше оставить HIGH до его разрешения
