### ISSUE TITLE
LOW: should be error instead of `valueOrElse`

### ISSUE THREAD

**Issue by vladislavpetushkov** [vladislavpetushkov/axly-smartcontract#4]
позиция может без займа быть, и в таком случае пользователь не сможет вывести средства.

**Comment by deemru** [comment]
Сейчас в коде есть ветвление по `borrowAmount`, поэтому при наличии `borrowAmount > 0` странно видеть в коде возможность появления `borrowAsset == ""`.

https://github.com/vladislavpetushkov/axly-smartcontract/blob/7162ffb300dae9b09209aa067063bfa96f52c487/main.ride#L607-L610

Если код плохо организован, что `borrowAsset` всё равно требуется, даже когда он не требуется, то это лучше переписать.

Или хотя бы добавить проверку, что он `borrowAsset != ""` при `borrowAmount > 0`.

**Comment by vladislavpetushkov** [comment]
переписал код
