### ISSUE TITLE
Values no checked at all

### ISSUE THREAD

**Issue by vladislavpetushkov** [vladislavpetushkov/axly-smartcontract#6]
не понятно что именно проверять при ините, адреса?

**Comment by deemru** [comment]
Всё проверять.

В базовом вариант: что адреса -- это адреса, что ассеты -- существуют, что ключ админа -- резолвится в адрес.

В идеале: что ещё и ожидаемые ключи на адресах на месте и система в целом в ожидаемом состоянии.

Приоритет не большой, но с этими проверками чуть спокойнее.
